apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendpod-8888
  labels:
    app: frontendpod-8888 
  namespace: project3ns 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendpod-8888 
  template:
    metadata:
      labels:
        app: frontendpod-8888 
        project: project3
        netzone: frontend
    spec:
      containers:
      - name: frontendpod-8888 
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        image: docker.io/byte13/alpine-k8s-tools
        ports:
        - containerPort: 8888
        command: [ "/K8SLAB/ncwebsrv.sh", "8888" ]
        #args: [ "while true; do cat /B13/HTML/index.html | nc -l -p 8888; done" ]
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/hostname: k8sworker12.lab.byte13.org
