apiVersion: v1
kind: Service
metadata:
  name: service-alpine-k8s-tools-8888
  #namespace: default
spec:
  #type: NodePort
  #externalTrafficPolicy: Cluster
  #externalTrafficPolicy: Local
  type: ClusterIP
  selector:
    app: frontendpod-8888 
  ports: 
    - protocol: TCP
      port: 8888
      targetPort: 8888
